[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "jinja2==2.10.3",
            "oldest-supported-numpy",
            "extension-helpers"]
build-backend = 'setuptools.build_meta'
